name: Python Tests

on:
  # Trigger this workflow on push or pull request to any branch
  push:
    branches:
      - main  # You can change this to your default branch name
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the environment to run the tests on (Ubuntu)

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python (specify the version)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements file

      # Step 4: Run tests using pytest
      - name: Run tests
        run: |
          pytest  # Adjust this to the test command you're using
